import "./globals.css";
import styles from "./page.module.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.content}>
          <h1 className={styles.title}>나도 문화인</h1>
        </div>
        <header className={styles.header}>
          <div className={styles.navbar}>
            <div>
              <div className={styles.navItem}>
                <p>오늘의</p>
                <p>공연/전시</p>
              </div>
              <div className={styles.navItem}>
                <p>내 주변</p>
                <p>공연/전시장</p>
              </div>
            </div>
            <p>로그인</p>
          </div>
        </header>
        <div className={styles.content}>{children}</div>
        <footer className={styles.footer}></footer>
      </body>
    </html>
  );
}
